import type { Adapter, FoundRoute } from "../adapter.ts";
import { parserFor, type SyntaxNode } from "../languages/tree-sitter.ts";
import { HTTP_METHODS, type HttpMethod } from "../types.ts";
import { singular } from "./inflect.ts";
import { allDefined, manifestsDeclaring, plainString, withheldList } from "./shared.ts";
import type { RailsRole } from "./taxonomy.ts";

// Rails routes are a DSL in config/routes.rb, and its expansions are fixed:
// `resources :photos` is seven actions on eight method-and-path pairs,
// `namespace :admin` puts /admin in front, `member` and `collection` hang
// routes off one record or the whole set. This walks the DSL the way Rails
// does and prints each pattern the way `rails routes` does, with the
// optional (.:format) suffix. Anything conditional, computed, generated by a
// gem's helper, or shaped by a concern is withheld.

const VERBS = new Map(HTTP_METHODS.map((m) => [m.toLowerCase(), m]));

const PLURAL_ACTIONS: readonly [string, HttpMethod, "collection" | "member", string][] = [
  ["index", "GET", "collection", ""],
  ["create", "POST", "collection", ""],
  ["new", "GET", "collection", "new"],
  ["edit", "GET", "member", "edit"],
  ["show", "GET", "member", ""],
  ["update", "PATCH", "member", ""],
  ["update", "PUT", "member", ""],
  ["destroy", "DELETE", "member", ""],
];
const SINGULAR_ACTIONS: readonly [string, HttpMethod, string][] = [
  ["new", "GET", "new"],
  ["create", "POST", ""],
  ["edit", "GET", "edit"],
  ["show", "GET", ""],
  ["update", "PATCH", ""],
  ["update", "PUT", ""],
  ["destroy", "DELETE", ""],
];

const ROLES: readonly (readonly [RailsRole, RegExp])[] = [
  ["routes", /(^|\/)config\/routes(\.rb|\/)/],
  ["concern", /(^|\/)app\/(models|controllers)\/concerns\//],
  ["controller", /(^|\/)app\/controllers\//],
  ["channel", /(^|\/)app\/channels\//],
  ["view", /(^|\/)app\/views\//],
  ["helper", /(^|\/)app\/helpers\//],
  ["serializer", /(^|\/)app\/serializers\//],
  ["model", /(^|\/)app\/models\//],
  ["mailer", /(^|\/)app\/mailers\//],
  ["job", /(^|\/)app\/jobs\//],
  ["migration", /(^|\/)db\/migrate\//],
  ["initializer", /(^|\/)config\/initializers\//],
];

/** Joins path pieces the way Rails normalises them: one slash between, none trailing, one leading. */
function joinPath(parts: readonly string[]): string {
  const p = parts.map((s) => s.replace(/^\/+|\/+$/g, "")).filter(Boolean).join("/");
  return `/${p}`.replace(/\/{2,}/g, "/");
}

type Ctx = {
  /** Path pieces so far. */
  path: string[];
  /** The resource whose block this is, if any. */
  resource: { collection: string[]; member: string[]; nested: string[] | null } | null;
  /** Inside `member do` / `collection do`. */
  on: "member" | "collection" | null;
  format: boolean;
};

const name = (n: SyntaxNode | null | undefined): string | null =>
  !n ? null : n.type === "simple_symbol" ? n.text.slice(1) : n.type === "hash_key_symbol" || n.type === "identifier" ? n.text : plainString(n);

type Args = { positional: SyntaxNode[]; options: Map<string, SyntaxNode> };

function argsOf(call: SyntaxNode): Args {
  const positional: SyntaxNode[] = [];
  const options = new Map<string, SyntaxNode>();
  const take = (n: SyntaxNode) => {
    if (n.type === "pair") {
      const k = n.childForFieldName("key");
      const key = name(k);
      const v = n.childForFieldName("value");
      // `get "photos/:id" => "photos#show"` is a path keyed to its endpoint.
      if (k && (k.type === "string") && v) positional.push(k);
      else if (key !== null && v) options.set(key, v);
    } else if (n.type === "hash") n.namedChildren.forEach(take);
    else positional.push(n);
  };
  call.childForFieldName("arguments")?.namedChildren.forEach(take);
  return { positional, options };
}

/** Symbols or strings, one or a list: only: [:index, :show]. Null if computed. */
function names(n: SyntaxNode | undefined): string[] | null {
  if (!n) return null;
  if (n.type === "array") {
    const out: string[] = [];
    for (const e of n.namedChildren) {
      const v = name(e);
      if (v === null) return null;
      out.push(v);
    }
    return out;
  }
  const v = name(n);
  return v === null ? null : [v];
}

function blockBody(call: SyntaxNode): SyntaxNode[] | null {
  const block = call.childForFieldName("block");
  if (!block) return null;
  const body = block.namedChildren.find((c) => c.type === "body_statement" || c.type === "block_body");
  return body ? body.namedChildren : [];
}

export const rails: Adapter = {
  name: "rails",
  claims: (input) => manifestsDeclaring(input, (p) => /(^|\/)Gemfile$/.test(p), (text) => /^\s*gem\s+['"](rails|railties)['"]/m.test(text)),
  reads: (path) => /\.(rb|erb|haml|slim|jbuilder|builder)$/.test(path),

  async analyze(scope) {
    const roles = new Map<string, string>();
    for (const f of scope.owned) {
      const role = ROLES.find(([, re]) => re.test(f.path))?.[0];
      if (role) roles.set(f.path, role);
    }

    const withheld = withheldList();
    const routes: FoundRoute[] = [];
    const parser = await parserFor("ruby");
    const trees: { delete(): void }[] = [];

    try {
      for (const root of scope.roots) {
        const base = root ? `${root}/` : "";
        const inflections = scope.read(`${base}config/initializers/inflections.rb`) ?? "";
        // An application's own inflection rules change what a nested parameter is called.
        const customInflections = inflections.split("\n").some((l) => /^\s*inflect\./.test(l));

        const emit = (file: string, line: number, method: HttpMethod, path: string, ctx: Ctx) =>
          routes.push({ file, method, path: path === "/" ? "/" : ctx.format ? `${path}(.:format)` : path, line });

        const readFile = (rel: string): SyntaxNode | null => {
          const text = scope.read(rel);
          if (text === null) return null;
          const tree = parser.parse(text);
          trees.push(tree);
          return tree.rootNode;
        };

        const walk = (file: string, statements: readonly SyntaxNode[], ctx: Ctx, depth: number) => {
          for (const stmt of statements) {
            const where = `${file}:${stmt.startPosition.row + 1}`;
            if (stmt.type === "comment") continue;
            if (stmt.type === "if" || stmt.type === "unless" || stmt.type === "case" || stmt.type === "if_modifier" || stmt.type === "unless_modifier") {
              withheld.add("routes declared inside a condition, so whether they exist depends on running the app", where);
              continue;
            }
            if (stmt.type !== "call" && stmt.type !== "identifier") continue;
            if (stmt.type === "call" && stmt.childForFieldName("receiver")) {
              withheld.add("a route-building call on an object, which isn't read", where);
              continue;
            }
            const method = stmt.type === "identifier" ? stmt.text : stmt.childForFieldName("method")?.text ?? "";
            const args = stmt.type === "call" ? argsOf(stmt) : { positional: [], options: new Map<string, SyntaxNode>() };
            const body = stmt.type === "call" ? blockBody(stmt) : null;
            const line = stmt.startPosition.row + 1;

            const format = args.options.get("format");
            const sub: Ctx = { ...ctx };
            if (format) {
              if (format.type === "false") sub.format = false;
              else {
                withheld.add("format: is set to something other than false, which changes the pattern in a way this doesn't read", where);
                continue;
              }
            }
            const pathOpt = args.options.get("path");
            const pathOptValue = pathOpt ? name(pathOpt) : undefined;
            if (pathOptValue === null) {
              withheld.add("path: isn't a plain string or symbol", where);
              continue;
            }

            switch (method) {
              case "draw": {
                const target = name(args.positional[0]);
                const rel = target === null ? null : `${base}config/routes/${target}.rb`;
                const tree = rel ? readFile(rel) : null;
                if (!tree || depth > 8) withheld.add("draw() names a routes file that couldn't be read", where);
                else walk(rel!, tree.namedChildren, ctx, depth + 1);
                break;
              }
              case "namespace":
              case "scope": {
                let segment: string | null = "";
                if (method === "namespace") segment = pathOptValue ?? name(args.positional[0]);
                else if (args.positional.length > 0) segment = name(args.positional[0]);
                else if (pathOptValue !== undefined) segment = pathOptValue;
                if (segment === null) {
                  withheld.add(`${method} path isn't a plain string or symbol`, where);
                  break;
                }
                if (body) walk(file, body, { ...sub, path: [...ctx.path, segment] }, depth);
                break;
              }
              case "constraints":
              case "defaults":
              case "controller":
                if (body) walk(file, body, sub, depth);
                break;
              case "member":
              case "collection":
                if (!ctx.resource) withheld.add(`${method} block outside a resource`, where);
                else if (body) walk(file, body, { ...sub, on: method }, depth);
                break;
              case "resources":
              case "resource": {
                const plural = method === "resources";
                if (args.options.has("concerns")) withheld.add("routes added by concerns aren't read", where);
                if (args.options.has("path_names") || args.options.has("shallow") || args.options.has("shallow_path")) {
                  withheld.add("resource with path_names or shallow nesting, which changes its paths in ways this doesn't read", where);
                  break;
                }
                const only = args.options.has("only") ? names(args.options.get("only")) : null;
                const except = args.options.has("except") ? names(args.options.get("except")) : null;
                if ((args.options.has("only") && only === null) || (args.options.has("except") && except === null)) {
                  withheld.add("only: or except: isn't a plain list of actions", where);
                  break;
                }
                const param = args.options.has("param") ? name(args.options.get("param")) : "id";
                if (param === null) {
                  withheld.add("param: isn't a plain symbol", where);
                  break;
                }
                const keep = (action: string) => (only === null || only.includes(action)) && (except === null || !except.includes(action));
                const resourceNames = allDefined(args.positional.map(name));
                if (resourceNames === null || resourceNames.length === 0 || (pathOpt && resourceNames.length > 1)) {
                  withheld.add("resource name isn't a plain symbol", where);
                  break;
                }
                for (const rn of resourceNames) {
                  // Inside another resource, a bare resource nests under that resource's record.
                  let at = ctx.path;
                  if (ctx.resource && ctx.on === null) {
                    if (ctx.resource.nested === null) {
                      withheld.add("nested under a resource whose parameter name can't be worked out", where);
                      continue;
                    }
                    at = ctx.resource.nested;
                  } else if (ctx.resource) at = ctx.on === "member" ? ctx.resource.member : ctx.resource.collection;
                  const collection = [...at, pathOptValue ?? rn];
                  const member = plural ? [...collection, `:${param}`] : collection;
                  if (plural) {
                    for (const [action, verb, on, suffix] of PLURAL_ACTIONS) {
                      if (keep(action)) emit(file, line, verb, joinPath([...(on === "member" ? member : collection), suffix]), sub);
                    }
                  } else {
                    for (const [action, verb, suffix] of SINGULAR_ACTIONS) {
                      if (keep(action)) emit(file, line, verb, joinPath([...collection, suffix]), sub);
                    }
                  }
                  if (body) {
                    const one = plural ? (customInflections ? null : singular(rn)) : null;
                    const nested = plural ? (one === null ? null : [...collection, `:${one}_${param}`]) : collection;
                    walk(file, body, { ...sub, resource: { collection, member, nested }, on: null }, depth);
                  }
                }
                break;
              }
              case "root": {
                if (args.options.has("via")) {
                  withheld.add("root with via:, which this doesn't read", where);
                  break;
                }
                // `root` is match "/": at the top it's "/", with no format; inside a
                // namespace it normalises to the namespace's path and takes one.
                emit(file, line, "GET", joinPath(ctx.path), sub);
                break;
              }
              case "match": {
                const via = names(args.options.get("via"));
                const path = name(args.positional[0]);
                if (via === null || via.includes("all")) {
                  withheld.add("match without a plain via: list answers methods this can't name", where);
                  break;
                }
                if (path === null) {
                  withheld.add("route path isn't a plain string or symbol", where);
                  break;
                }
                const verbs = allDefined(via.map((v) => VERBS.get(v)));
                if (verbs === null) {
                  withheld.add("via: names a method the route table doesn't carry", where);
                  break;
                }
                const at = placement(ctx, args, where);
                if (at) for (const v of verbs) emit(file, line, v, joinPath([...at, path]), sub);
                break;
              }
              case "mount":
                withheld.add("a mounted engine or Rack app: its routes are defined inside it", where);
                break;
              case "concern":
              case "concerns":
                withheld.add("routes added by concerns aren't read", where);
                break;
              case "direct":
              case "resolve":
                break;
              default: {
                const verb = VERBS.get(method);
                if (!verb) {
                  withheld.add(`routes generated by \`${method}\` (a helper or gem), which aren't read`, where);
                  break;
                }
                const path = name(args.positional[0]) ?? (args.positional.length === 0 && pathOptValue ? pathOptValue : null);
                if (path === null) {
                  withheld.add("route path isn't a plain string or symbol", where);
                  break;
                }
                const at = placement(ctx, args, where);
                if (at) emit(file, line, verb, joinPath([...at, pathOptValue ?? path]), sub);
              }
            }
          }
        };

        /** Where a verb route sits: plain, on a resource's member or collection, or nested under its record. */
        const placement = (ctx: Ctx, args: Args, where: string): string[] | null => {
          if (!ctx.resource) return ctx.path;
          const on = args.options.has("on") ? name(args.options.get("on")) : ctx.on;
          if (on === "member") return ctx.resource.member;
          if (on === "collection") return ctx.resource.collection;
          if (on !== null) {
            withheld.add("on: isn't :member or :collection", where);
            return null;
          }
          if (ctx.resource.nested === null) {
            withheld.add("nested under a resource whose parameter name can't be worked out", where);
            return null;
          }
          return ctx.resource.nested;
        };

        const routesFile = `${base}config/routes.rb`;
        const tree = readFile(routesFile);
        if (!tree) continue;
        const draws = tree.descendantsOfType("call").filter((c) => c.childForFieldName("method")?.text === "draw" && c.childForFieldName("receiver") && c.childForFieldName("block"));
        if (draws.length !== 1) {
          withheld.add("config/routes.rb doesn't have one routes.draw block", routesFile);
          continue;
        }
        walk(routesFile, blockBody(draws[0]) ?? [], { path: [], resource: null, on: null, format: true }, 0);
      }
    } finally {
      for (const t of trees) t.delete();
      parser.delete();
    }

    const seen = new Set<string>();
    const unique = routes.filter((r) => {
      const key = `${r.file}\n${r.method}\n${r.path}`;
      if (seen.has(key)) return false;
      seen.add(key);
      return true;
    });
    return { roles, routes: unique, routesWithheld: withheld.list() };
  },
};
